#!/bin/bash

#Custermize this for your application
APPLICATION_FILE_PATH=tunneld

#Parameters
PRODUCT_HOME=/Library/__PRODUCT__/__VERSION__

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

#Add application shortcut to /usr/local/bin
rm -f /usr/local/bin/__PRODUCT__
ln -s ${PRODUCT_HOME}/${APPLICATION_FILE_PATH} /usr/local/bin/__PRODUCT__

APPLICATION_PLIST_NAME=__GROUP__.__PRODUCT__
APPLICATION_PLIST_FILE=${APPLICATION_PLIST_NAME}.plist
if [ -f ${PRODUCT_HOME}/${APPLICATION_PLIST_FILE} ]; then
  echo "Install ${APPLICATION_PLIST_FILE}"
  cp ${PRODUCT_HOME}/${APPLICATION_PLIST_FILE} /Library/LaunchDaemons/

  # Replace __HOME__ with user home directory
  echo "dump home $HOME"
  sed -i '' "s|__HOME__|$HOME|g" "/Library/LaunchDaemons/${APPLICATION_PLIST_FILE}"

  # enable and start the service
  launchctl bootout system/${APPLICATION_PLIST_NAME}
  launchctl load -w /Library/LaunchDaemons/${APPLICATION_PLIST_FILE}
fi

echo "Post installation process finished"
